#pragma once

#include <string>
#include <vector>

#include <glad/glad.h>
#include "core/img/ibl.h"

namespace gfx::cubemap {

    class Cube {

        static unsigned int vbo, vao;
        Cube();

    public:

        static const unsigned int getVAO() {

            static Cube instance {};
            return instance.vao;
        }

        static void draw() {

            glBindVertexArray(vao);
            glDrawArrays(GL_TRIANGLES, 0, 36);
            glBindVertexArray(0);
        }
    };
};

class CubeMap {
    
    unsigned int textureID;

public:

    /* 
    Cubemap with custom modifications 
    @param internal_format GL_RGB / GL_SRGB / GL_RGB16F (for HDR)
    @param type GL_UNSIGNED_BYTE / GL_FLOAT
    @param res_size Resolution of the Texture
    */
    CubeMap(const std::vector <std::string>& textureFaces, const uint16_t internal_format, const uint16_t type, const uint16_t res_size);

    /* Cubemap designed for Irradiance Maps. @param res_size Resolution of the Irradiance Map */
    CubeMap(const std::vector <std::string>& textureFaces, const uint16_t res_size) : CubeMap(textureFaces, GL_RGB, GL_UNSIGNED_BYTE, res_size) {}

    /* General purpose cubemap */
    CubeMap(const std::vector <std::string>& textureFaces) : CubeMap(textureFaces, GL_SRGB8, GL_UNSIGNED_BYTE, 0) {}

    void bindTexture(const unsigned int textureUnit) const;
    void destroy();
};

class Environment {

    CubeMap* m_cubeMap;
    CubeMap* m_irradianceMap;
    
    bool isVisible;

    IBLFrame* iblFrame;

public:

    Environment(const char* path, const uint16_t resolution = 512);
    Environment(const std::vector <std::string>& textureFaces);

    void setVisibility(const bool visible) { isVisible = visible; }
    bool getVisibility() const { return isVisible; }

    // @note IrradianceMap is auto-generated by default.
    // Use this function if irradiance map textures (images) are available.
    void setIrradianceMap(const std::vector <std::string>& textureFaces);

    void bindTexture(const unsigned int textureUnit) const;
    void bindIrradiance(const unsigned int textureUni) const;
    void bindPrefilter(const unsigned int textureUnit) const;
    void bindBRDF(const unsigned int textureUnit) const;

    void draw() const;
    void destroy();
};